// f12 — topology arms for A50 §4 (H5295 falsification ledger).
//
// A50 §4 reads "significantly modular, not nested" (Barber Q vs a
// degree-preserving null) as "the dictionaries fall into partly disjoint
// citation communities". This harness asks whether the statistic identifies
// that mechanism, by re-running the SAME committed test
// (scripts/build-citation-canon.mjs: same NODF, same LPAwb+ modularity, same
// seeded 1,000-sample fixed-fixed null) on eight matrices plus a seed×fraction
// sweep of the constructed control:
//
//   A0 committed      the committed edge list as is (reproduction + module
//                     read-out: WHICH dictionaries share a module).
//   A1 folded         the same edges after folding the transliteration
//                     variants listed in data/forensic/f12_a50_variant_fold.tsv
//                     (the four §5.5 names + every ASCII-fold collision).
//                     A50 §5.5 asserts folding "would only sharpen" the
//                     modularity result — this arm measures the direction.
//   A2 nine-rows      mw and md dropped (5 and 4 nodes; the paper's own
//                     "unrepresentative yield" rows).
//   A3 one-canon      CONSTRUCTED: one ranked canon, dictionary k samples n_k
//                     texts (n_k = the real per-dictionary breadths) with
//                     weight 1/(rank+1) — one reading list read to different
//                     depths; no communities. (Not perfectly nested: see the
//                     note at oneCanonEdges — a Ferrers matrix hangs the null.)
//   A4 one-canon+spell CONSTRUCTED: A3 plus per-dictionary private spelling
//                     of a fraction f of each row's texts (the text is still
//                     the same text; only its node label diverges). Still
//                     one canon, still no communities. Relabelling changes
//                     the column margins, so the null is re-drawn on the new
//                     margins — the comparison is observed-vs-null per arm,
//                     never raw Q across arms.
//   SWEEP             A4 over fractions × seeds (SWEEP_FRACTIONS ×
//                     SWEEP_SEEDS), so a verdict at one seed is not mistaken
//                     for a property of the mechanism. Reported per run:
//                     Q, null mean/SD, z, p, verdict; summarised as the share
//                     of runs the test calls modular / nested.
//   A5 regen@f4c08c57 the edge list regenerated by build_ls_citation_graph.py
//                     against sibling csl-orig@f4c08c57 (24-09-2026 audit
//                     run), if data/forensic/f12_a50_regen_edges.tsv exists —
//                     shows whether the unrecorded-revision drift moves the
//                     verdict.
//
// Deterministic (seed 0x5eedca11 as in the committed test). Output:
//   data/forensic/f12_a50_topology_arms.json
// Usage: node scripts/forensic/f12_a50_topology_arms.mjs

import fs from "node:fs";
import crypto from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { buildMatrix, permutationTest, modularity, mulberry32 } from "../build-citation-canon.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..", "..");
const EDGES = path.join(ROOT, "data", "citations", "ls_citation_edges.tsv");
const NODES = path.join(ROOT, "data", "citations", "ls_citation_nodes.tsv");
const FOLD = path.join(ROOT, "data", "forensic", "f12_a50_variant_fold.tsv");
const REGEN = path.join(ROOT, "data", "forensic", "f12_a50_regen_edges.tsv");
const OUT = path.join(ROOT, "data", "forensic", "f12_a50_topology_arms.json");
const SEED = 0x5eedca11;
const SPELL_FRACTIONS = [0.1, 0.3];
const SWEEP_FRACTIONS = [0.05, 0.1, 0.2, 0.3];
const SWEEP_SEEDS = [1, 2, 3];
const QUICK = process.argv.includes("--quick"); // skip the sweep (dev runs)
// csl-atlas HEAD + dirty flag, so the JSON is bound to a checkout, not a path.
function gitState() {
  try {
    const revision = execSync("git rev-parse HEAD", { encoding: "utf8", cwd: ROOT }).trim();
    const dirty = execSync("git status --porcelain", { encoding: "utf8", cwd: ROOT }).trim().length > 0;
    return { revision, dirty };
  } catch (e) {
    return { revision: `unavailable: ${e?.code ?? e?.name ?? "error"}`, dirty: null };
  }
}

const sha256 = (p) => (fs.existsSync(p) ? crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex") : null);
// z from the builder's unrounded null moments when it reports one (build-citation-canon.mjs
// computes z before rounding nullMean/nullSd); recomputed from rounded values only as a fallback.
const z = (obs, mean, sd, given) => (typeof given === "number" ? given : sd > 0 ? Number(((obs - mean) / sd).toFixed(2)) : null);

function parseTsv(text) {
  const lines = text.replace(/\r\n/g, "\n").split("\n").filter((l) => l.length > 0);
  const header = lines[0].split("\t");
  return lines.slice(1).map((line) => {
    const cells = line.split("\t");
    const row = {};
    header.forEach((h, i) => (row[h] = cells[i] ?? ""));
    return row;
  });
}

function nodesFromEdges(edgeRows) {
  const total = new Map();
  const dicts = new Map();
  for (const e of edgeRows) {
    total.set(e.canonical_text, (total.get(e.canonical_text) || 0) + Number(e.count));
    if (!dicts.has(e.canonical_text)) dicts.set(e.canonical_text, new Set());
    dicts.get(e.canonical_text).add(e.dict);
  }
  return [...total.keys()].map((t) => ({
    canonical_text: t,
    total_cites: String(total.get(t)),
    n_dicts: String(dicts.get(t).size),
    variant_forms: ""
  }));
}

function foldEdges(edgeRows, foldMap) {
  const merged = new Map();
  for (const e of edgeRows) {
    const text = foldMap.get(e.canonical_text) || e.canonical_text;
    const key = `${e.dict}\t${text}`;
    merged.set(key, (merged.get(key) || 0) + Number(e.count));
  }
  return [...merged.entries()].map(([k, count]) => {
    const [dict, canonical_text] = k.split("\t");
    return { dict, canonical_text, count: String(count) };
  });
}

// Module read-out on the observed matrix only (same optimiser, same seed as
// the committed test's observed run).
function moduleReadout(matrix) {
  const res = modularity(matrix.rowSets, matrix.texts.length, mulberry32(SEED ^ 0x1234));
  const byLabel = new Map();
  matrix.dicts.forEach((d, i) => {
    const L = res.rowLabels[i];
    if (!byLabel.has(L)) byLabel.set(L, []);
    byLabel.get(L).push(d);
  });
  const groups = [...byLabel.values()].sort((a, b) => b.length - a.length || (a[0] < b[0] ? -1 : 1));
  return { q: Number(res.q.toFixed(4)), nModules: res.nModules, dictGroups: groups };
}

function runArm(name, edgeRows, note) {
  const nodeRows = nodesFromEdges(edgeRows);
  const matrix = buildMatrix(edgeRows, nodeRows);
  const stats = permutationTest(matrix, mulberry32(SEED));
  const nested = stats.nodf.p <= 0.05 && stats.nodf.observed > stats.nodf.nullMean;
  const modular = stats.modularity.p <= 0.05 && stats.modularity.observed > stats.modularity.nullMean;
  const verdict = nested && !modular ? "nested" : modular && !nested ? "modular" : nested && modular ? "nested-and-modular" : "neither-detected";
  const nEdges = matrix.rowSets.reduce((a, s) => a + s.size, 0);
  const privateCols = matrix.texts.filter((t) => matrix.textDictCount.get(t) === 1).length;
  const readout = moduleReadout(matrix);
  const arm = {
    name,
    note,
    matrix: { nDicts: matrix.dicts.length, nTexts: matrix.texts.length, nEdges, privateTexts: privateCols },
    nodf: { ...stats.nodf, z: z(stats.nodf.observed, stats.nodf.nullMean, stats.nodf.nullSd, stats.nodf.z) },
    modularity: {
      ...stats.modularity,
      z: z(stats.modularity.observed, stats.modularity.nullMean, stats.modularity.nullSd, stats.modularity.z),
      marginOverNull: Number((stats.modularity.observed - stats.modularity.nullMean).toFixed(4))
    },
    verdict,
    dictModules: readout.dictGroups
  };
  console.log(
    `${name.padEnd(22)} ${String(matrix.dicts.length).padStart(2)}×${String(matrix.texts.length).padStart(4)} ` +
      `NODF ${stats.nodf.observed} (null ${stats.nodf.nullMean}, p ${stats.nodf.p}) ` +
      `Q ${stats.modularity.observed} (null ${stats.modularity.nullMean}, p ${stats.modularity.p}) → ${verdict}; ` +
      `dict modules: ${readout.dictGroups.map((g) => g.join("+")).join(" | ")}`
  );
  return arm;
}

// ---- constructed arms -------------------------------------------------------
// A PERFECTLY nested matrix (dictionary k cites exactly the top n_k texts) is
// the unique realisation of its row and column margins, so the committed
// fixed-fixed swap null has nowhere to move and its burn-in loop never
// terminates (first run of this harness, 24-09-2026). The constructed canon is
// therefore rank-BIASED rather than rank-truncated: every dictionary samples
// its n_k texts without replacement from one ranked canon with weight
// 1/(rank+1), so the head is shared by everyone and the tails overlap only
// partly — one reading list, read to different depths, no communities.
function oneCanonEdges(breadths, nCanon, rng) {
  const edges = [];
  for (const { dict, n } of breadths) {
    const weights = Array.from({ length: nCanon }, (_, i) => 1 / (i + 1));
    const chosen = new Set();
    while (chosen.size < n) {
      let total = 0;
      for (let i = 0; i < nCanon; i += 1) if (!chosen.has(i)) total += weights[i];
      let r = rng() * total;
      for (let i = 0; i < nCanon; i += 1) {
        if (chosen.has(i)) continue;
        r -= weights[i];
        if (r <= 0) {
          chosen.add(i);
          break;
        }
      }
    }
    for (const i of [...chosen].sort((a, b) => a - b)) {
      edges.push({ dict, canonical_text: `T${String(i).padStart(4, "0")}`, count: "1" });
    }
  }
  return edges;
}

function withPrivateSpelling(edges, fraction, rng) {
  // Relabel a seeded fraction of each dictionary's edges to a dictionary-
  // private node name. The cited TEXT is unchanged; only the label diverges —
  // exactly what an unfolded transliteration variant does in the real graph.
  return edges.map((e) => (rng() < fraction ? { ...e, canonical_text: `${e.canonical_text}@${e.dict}` } : e));
}

function main() {
  const edgeRows = parseTsv(fs.readFileSync(EDGES, "utf8"));
  const arms = [];

  arms.push(runArm("A0-committed", edgeRows, "committed ls_citation_edges.tsv; reproduction + module read-out"));

  if (fs.existsSync(FOLD)) {
    const foldRows = parseTsv(fs.readFileSync(FOLD, "utf8"));
    const named = new Map(foldRows.filter((r) => r.tier === "named").map((r) => [r.variant, r.canonical]));
    const all = new Map(foldRows.map((r) => [r.variant, r.canonical]));
    arms.push(runArm("A1a-folded-named", foldEdges(edgeRows, named), `the four §5.5 variants folded (${named.size} rows)`));
    arms.push(runArm("A1b-folded-ascii", foldEdges(edgeRows, all), `all ASCII-fold collisions folded (${all.size} rows; upper bound on curated folding)`));
  }

  arms.push(runArm("A2-nine-rows", edgeRows.filter((e) => e.dict !== "mw" && e.dict !== "md"), "mw and md dropped (5 and 4 nodes)"));

  // Real per-dictionary breadths from the committed matrix, for the constructed arms.
  const breadthMap = new Map();
  for (const e of edgeRows) breadthMap.set(e.dict, (breadthMap.get(e.dict) || 0) + 1);
  const breadths = [...breadthMap.entries()].map(([dict, n]) => ({ dict, n }));
  const nCanon = new Set(edgeRows.map((e) => e.canonical_text)).size;
  const canon = oneCanonEdges(breadths, nCanon, mulberry32(SEED ^ 0xa3));
  arms.push(runArm("A3-one-canon", canon, "constructed: one ranked canon sampled rank-biased (weight 1/(rank+1)) to the real breadths; one reading list, no communities"));
  for (const f of SPELL_FRACTIONS) {
    const spelled = withPrivateSpelling(canon, f, mulberry32(SEED ^ Math.round(f * 1000)));
    arms.push(runArm(`A4-one-canon-spell-${f}`, spelled, `constructed: A3 with a ${f} fraction of each row relabelled to a dictionary-private spelling; still one canon`));
  }

  if (fs.existsSync(REGEN)) {
    arms.push(runArm("A5-regen-f4c08c57", parseTsv(fs.readFileSync(REGEN, "utf8")), "edge list regenerated at sibling csl-orig@f4c08c57 / csl-guides@64c967d (24-09-2026)"));
  }

  // Seed × fraction sweep of the constructed control (X1 of the 24-09-2026
  // critic: one seed at one fraction is not evidence about a mechanism).
  const sweep = [];
  if (!QUICK) {
    for (const seed of SWEEP_SEEDS) {
      const canonS = oneCanonEdges(breadths, nCanon, mulberry32(SEED ^ 0xa3 ^ seed));
      for (const f of SWEEP_FRACTIONS) {
        const spelled = withPrivateSpelling(canonS, f, mulberry32(SEED ^ Math.round(f * 1000) ^ (seed << 8)));
        const arm = runArm(`S-seed${seed}-f${f}`, spelled, `sweep: one canon (seed ${seed}) with fraction ${f} relabelled`);
        sweep.push({ seed, fraction: f, matrix: arm.matrix, nodf: arm.nodf, modularity: arm.modularity, verdict: arm.verdict, nModulesObserved: arm.dictModules.length });
      }
    }
  }
  const sweepSummary = sweep.length
    ? {
        runs: sweep.length,
        modular: sweep.filter((r) => r.verdict === "modular").length,
        nested: sweep.filter((r) => r.verdict === "nested").length,
        nestedAndModular: sweep.filter((r) => r.verdict === "nested-and-modular").length,
        neither: sweep.filter((r) => r.verdict === "neither-detected").length,
        maxMarginOverNull: Math.max(...sweep.map((r) => r.modularity.marginOverNull)),
        maxModularityZ: Math.max(...sweep.map((r) => r.modularity.z ?? -Infinity)),
        byFraction: Object.fromEntries(
          SWEEP_FRACTIONS.map((f) => [
            String(f),
            sweep.filter((r) => r.fraction === f).map((r) => `${r.verdict} (Q−null ${r.modularity.marginOverNull}, z ${r.modularity.z}, p ${r.modularity.p})`)
          ])
        )
      }
    : null;

  const payload = {
    handoff: "H5295",
    script: "scripts/forensic/f12_a50_topology_arms.mjs",
    scriptSha256: sha256(fileURLToPath(import.meta.url)),
    testScript: "scripts/build-citation-canon.mjs",
    cslAtlas: gitState(),
    seed: SEED,
    nNull: arms[0].modularity.nNull,
    inputs: {
      "data/citations/ls_citation_edges.tsv": sha256(EDGES),
      "data/forensic/f12_a50_variant_fold.tsv": sha256(FOLD),
      "data/forensic/f12_a50_regen_edges.tsv": sha256(REGEN),
      "scripts/build-citation-canon.mjs": sha256(path.join(ROOT, "scripts", "build-citation-canon.mjs"))
    },
    arms,
    sweep,
    sweepSummary
  };
  fs.writeFileSync(OUT, `${JSON.stringify(payload, null, 2)}\n`);
  console.log(`wrote ${path.relative(ROOT, OUT)}`);
}

main();
