#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""f12 — falsification ledger for A50's decision-bearing claims (H5295).

The question this script exists to answer
-----------------------------------------
A50 (``docs/articles/A50_ls_citation_frequency_graph.md``) reads the committed
``<ls>`` citation graph (``data/citations/``) as evidence about *the Sanskrit
lexicographic tradition*: concentration, a thin shared canon, and a
significantly modular arrangement read as tradition communities. Every number
in the paper reproduces from the committed TSVs (checked here again). What this
script tests is the **inferential step** on top of each number — whether the
measured quantity actually identifies the thing the sentence says, or whether
a mechanism with no "tradition" in it produces the same figure.

Claims audited (stable IDs, used in the ledger doc and the PR)
--------------------------------------------------------------
  A50-C1  §3 concentration — "the tradition's citation mass is heavily
          concentrated: top 10 = 33.7 %, top 50 = 71.0 %".
          Alternative: the pooled graph is 64.7 % PWG, so the pooled
          concentration may be PWG's own profile, not the tradition's.
  A50-C2  §3 reach — "no text is cited by all 11 dictionaries" and "608 of 912
          texts (66.7 %) are private to a single dictionary".
          Alternatives: (a) two rows (mw: 5 nodes, md: 4 nodes) make "all 11"
          mechanically unreachable for every text they do not happen to hit;
          (b) unfolded transliteration variants of shared texts sit in the
          private tail as separate nodes (§5.5 names four; there are more).
  A50-C3  §4 topology — "significantly modular, not nested" ⇒ "the
          dictionaries fall into partly disjoint citation communities".
          Alternative: per-dictionary spelling of a SHARED canon produces
          dictionary-private nodes and therefore modularity with no community
          structure at all. Tested in ``f12_a50_topology_arms.mjs`` (folded
          arm, 9-dict arm, and a constructed single-canon counterexample).
  A50-C4  §4 naming — the four named communities (Buddhist / kāvya / Vedic /
          Petersburg) are attributed to the modularity result.
          Alternative: the optimiser's 9 modules may not group dictionaries
          that way at all; the names come from the tradition map, not from
          the topology. Module membership is read out in the arms harness.
  A50-C5  §3 "the Western dictionaries cite the Indian dictionaries, descent
          made visible as citation".
          Alternative: one Western dictionary (PWG) cites the kośas; the
          others cite them in the tens. Measured per dictionary below.
  A50-C6  §5.5 directional claim — "the modularity result … would only
          sharpen if variants of shared texts were folded".
          Tested directly by the folded arm in the arms harness; this script
          produces the fold map it uses.

Outputs (committed)
-------------------
  data/forensic/f12_a50_report.json        every figure below + input hashes
  data/forensic/f12_a50_variant_fold.tsv   variant → canonical fold map
                                           (two tiers: ``named`` = the four
                                           §5.5 variants; ``ascii`` = every
                                           node pair whose aggressive ASCII
                                           fold collides — an UPPER bound on
                                           legitimate folding, reviewed by eye
                                           in the ledger doc)

Deterministic, offline: reads only the two committed TSVs. No corpus read.
Regenerate with::

    python scripts/forensic/f12_a50_claim_ledger.py
"""
from __future__ import annotations


import collections
import csv
import hashlib
import json
import os
import re
import sys
import subprocess
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
EDGES = os.path.join(ROOT, "data", "citations", "ls_citation_edges.tsv")
NODES = os.path.join(ROOT, "data", "citations", "ls_citation_nodes.tsv")
CANON = os.path.join(ROOT, "src", "data", "citations", "citation_canon.json")
OUT_JSON = os.path.join(ROOT, "data", "forensic", "f12_a50_report.json")
OUT_FOLD = os.path.join(ROOT, "data", "forensic", "f12_a50_variant_fold.tsv")
# Edge list regenerated by the builder at a recorded sibling revision (optional):
# when present, the report carries a `drift` block comparing every headline figure.
REGEN = os.path.join(ROOT, "data", "forensic", "f12_a50_regen_edges.tsv")

# The four variants A50 §5.5 names by hand (variant -> canonical node).
NAMED_VARIANTS = {
    "Raghuvanśa": "Raghuvaṃśa",
    "Manusmṛiti": "Manusmṛti",
    "Rigveda": "Ṛgveda",
    "Bhāgavata": "Bhāgavata-Purāṇa",
}

# Rows the paper itself flags as unrepresentative yields (§5.2, Table 3 note).
THIN_ROWS = {"mw", "md"}

# The four indigenous lexica §3 names as "among the most-cited sources".
KOSAS = ["Śabdakalpadruma", "Amarakoṣa", "Abhidhānacintāmaṇi", "Medinīkośa"]


def git_state() -> dict:
    """csl-atlas HEAD + dirty flag, so the report is bound to a checkout, not a path."""
    try:
        rev = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        dirty = bool(subprocess.run(["git", "status", "--porcelain"], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip())
        return {"revision": rev, "dirty": dirty}
    except Exception as exc:  # noqa: BLE001 — provenance must never abort the report
        return {"revision": f"unavailable: {type(exc).__name__}", "dirty": None}


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_tsv(path: str):
    with open(path, encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def ascii_fold(name: str) -> str:
    """Aggressive transliteration-insensitive key.

    Deliberately coarser than the builder's ``fold_key`` (which only strips
    diacritics and case): it also collapses the Anglo-Indian digraphs
    (sh→s, ch→c, ri→r) and doubled letters that separate ``Naishadhacharita``
    from ``Naiṣadhacarita``. Coarse on purpose — it is the UPPER bound on what
    a curated alias table could fold, and every collision it produces is
    listed for eye review, never applied blind.
    """
    s = unicodedata.normalize("NFD", name)
    s = "".join(ch for ch in s if unicodedata.category(ch) != "Mn").lower()
    s = re.sub(r"\(.*?\)", "", s)
    s = s.replace("-", "").replace(" ", "")
    for a, b in (("sh", "s"), ("ri", "r"), ("ch", "c"), ("ii", "i"), ("aa", "a"), ("uu", "u")):
        s = s.replace(a, b)
    s = re.sub(r"[^a-z]", "", s)
    s = re.sub(r"(.)\1+", r"\1", s)
    return s


def topk_share(counter: collections.Counter, ks=(10, 20, 50, 100)) -> dict:
    total = sum(counter.values())
    vals = sorted(counter.values(), reverse=True)
    return {str(k): round(100.0 * sum(vals[:k]) / total, 1) for k in ks}


def reach_table(dicts_of: dict, exclude=frozenset()) -> dict:
    counter = collections.Counter()
    for ds in dicts_of.values():
        k = len(set(ds) - exclude)
        if k:
            counter[k] += 1
    return {str(k): counter[k] for k in sorted(counter, reverse=True)}


def headline(edges: list) -> dict:
    """Every figure the paper's Abstract/§3 quote, from an edge list alone —
    used for the committed TSV and for a regenerated one, so drift is measured
    on the same arithmetic."""
    total = sum(e["count"] for e in edges)
    by_text = collections.Counter()
    by_dict = collections.Counter()
    dicts_of = collections.defaultdict(set)
    for e in edges:
        by_text[e["canonical_text"]] += e["count"]
        by_dict[e["dict"]] += e["count"]
        dicts_of[e["canonical_text"]].add(e["dict"])
    private = [t for t, ds in dicts_of.items() if len(ds) == 1]
    ge7 = [t for t, ds in dicts_of.items() if len(ds) >= 7]
    return {
        "cites": total,
        "edges": len(edges),
        "nodes": len(by_text),
        "topk_share_pooled_pct": topk_share(by_text),
        "pwg_volume_share_pct": round(100.0 * by_dict.get("pwg", 0) / total, 1) if total else None,
        "private_nodes": len(private),
        "private_nodes_pct": round(100.0 * len(private) / len(by_text), 1) if by_text else None,
        "private_volume_pct": round(100.0 * sum(by_text[t] for t in private) / total, 1) if total else None,
        "texts_ge7_dicts": len(ge7),
        "texts_ge7_volume_pct": round(100.0 * sum(by_text[t] for t in ge7) / total, 1) if total else None,
        "reach_max": max((len(ds) for ds in dicts_of.values()), default=0),
        "per_dict_cites": dict(sorted(by_dict.items())),
        "per_dict_texts": {d: sum(1 for t in dicts_of if d in dicts_of[t]) for d in sorted(by_dict)},
    }


def drift(committed: list, regen: list) -> dict:
    """Committed vs regenerated edge list: headline figures side by side, the
    per-dictionary deltas, node-set differences and the largest edge moves."""
    a, b = headline(committed), headline(regen)
    ka = {(e["dict"], e["canonical_text"]): e["count"] for e in committed}
    kb = {(e["dict"], e["canonical_text"]): e["count"] for e in regen}
    moves = [(k, ka.get(k, 0), kb.get(k, 0)) for k in set(ka) | set(kb) if ka.get(k, 0) != kb.get(k, 0)]
    moves.sort(key=lambda m: (-abs(m[1] - m[2]), m[0]))
    na = {e["canonical_text"] for e in committed}
    nb = {e["canonical_text"] for e in regen}
    return {
        "regen_sha256": sha256(REGEN),
        "committed": a,
        "regenerated": b,
        "headline_moves": {
            k: [a[k], b[k]] for k in ("cites", "edges", "nodes", "pwg_volume_share_pct", "private_nodes",
                                      "private_nodes_pct", "private_volume_pct", "texts_ge7_dicts",
                                      "texts_ge7_volume_pct", "reach_max") if a[k] != b[k]
        },
        "topk_moves": {k: [a["topk_share_pooled_pct"][k], b["topk_share_pooled_pct"][k]]
                       for k in a["topk_share_pooled_pct"] if a["topk_share_pooled_pct"][k] != b["topk_share_pooled_pct"][k]},
        "dicts_with_changed_cites": {d: [a["per_dict_cites"][d], b["per_dict_cites"].get(d)]
                                     for d in a["per_dict_cites"] if a["per_dict_cites"][d] != b["per_dict_cites"].get(d)},
        "nodes_only_committed": sorted(na - nb),
        "nodes_only_regenerated": sorted(nb - na),
        "edges_changed": len(moves),
        "largest_edge_moves": [{"dict": k[0], "text": k[1], "committed": x, "regenerated": y} for k, x, y in moves[:12]],
    }


def main() -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")
    edges = read_tsv(EDGES)
    nodes = read_tsv(NODES)
    for e in edges:
        e["count"] = int(e["count"])

    total = sum(e["count"] for e in edges)
    by_dict = collections.Counter()
    by_text = collections.Counter()
    dicts_of = collections.defaultdict(set)
    per_dict_text = collections.defaultdict(collections.Counter)
    for e in edges:
        by_dict[e["dict"]] += e["count"]
        by_text[e["canonical_text"]] += e["count"]
        dicts_of[e["canonical_text"]].add(e["dict"])
        per_dict_text[e["dict"]][e["canonical_text"]] += e["count"]

    report: dict = {
        "handoff": "H5295",
        "script": "scripts/forensic/f12_a50_claim_ledger.py",
        "script_sha256": sha256(os.path.abspath(__file__)),
        "csl_atlas": git_state(),
        "inputs": {
            os.path.relpath(p, ROOT): sha256(p) for p in (EDGES, NODES, CANON)
        },
        "totals": {"cites": total, "edges": len(edges), "nodes": len(nodes)},
    }

    # ---- A50-C1 concentration ------------------------------------------------
    no_pwg = collections.Counter()
    for e in edges:
        if e["dict"] != "pwg":
            no_pwg[e["canonical_text"]] += e["count"]
    report["C1_concentration"] = {
        "per_dict_volume_share_pct": {d: round(100.0 * v / total, 1) for d, v in by_dict.most_common()},
        "topk_share_pooled_pct": topk_share(by_text),
        "topk_share_excluding_pwg_pct": topk_share(no_pwg),
        "texts_excluding_pwg": len(no_pwg),
        "per_dict_top10_share_pct": {
            d: topk_share(c, (10,))["10"] for d, c in sorted(per_dict_text.items())
        },
    }

    # ---- A50-C2 reach + private tail ----------------------------------------
    private = [t for t, ds in dicts_of.items() if len(ds) == 1]
    private_vol = sum(by_text[t] for t in private)
    n_usable = len(set(by_dict) - THIN_ROWS)
    all_usable = sorted(t for t, ds in dicts_of.items() if len(ds - THIN_ROWS) == n_usable)
    ge7 = [t for t, ds in dicts_of.items() if len(ds) >= 7]
    report["C2_reach"] = {
        "reach_all_11": reach_table(dicts_of),
        "reach_excluding_thin_rows": reach_table(dicts_of, frozenset(THIN_ROWS)),
        "thin_rows": sorted(THIN_ROWS),
        "thin_row_node_counts": {d: len(per_dict_text[d]) for d in sorted(THIN_ROWS & set(by_dict))},
        "usable_rows": n_usable,
        "texts_cited_by_every_usable_row": all_usable,
        "private_nodes": len(private),
        "private_nodes_pct": round(100.0 * len(private) / len(dicts_of), 1),
        "private_volume_pct": round(100.0 * private_vol / total, 1),
        "private_by_dict": dict(collections.Counter(next(iter(dicts_of[t])) for t in private).most_common()),
        "texts_ge7_dicts": len(ge7),
        "texts_ge7_volume_pct": round(100.0 * sum(by_text[t] for t in ge7) / total, 1),
    }

    # ---- variant fold map (feeds C2b + C3 folded arm) ------------------------
    groups = collections.defaultdict(list)
    for t in dicts_of:
        key = ascii_fold(t)
        if key:  # non-Latin noise nodes fold to "" — never a real variant pair
            groups[key].append(t)
    fold_rows = []  # (variant, canonical, tier, variant_cites, variant_dicts, canonical_dicts)
    for variant, canonical in NAMED_VARIANTS.items():
        if variant in dicts_of and canonical in dicts_of:
            fold_rows.append((variant, canonical, "named"))
    for key, members in groups.items():
        if len(members) < 2:
            continue
        # canonical = the member cited by most dictionaries, then most cites.
        members = sorted(members, key=lambda t: (-len(dicts_of[t]), -by_text[t], t))
        canonical = members[0]
        for v in members[1:]:
            if any(r[0] == v for r in fold_rows):
                continue
            fold_rows.append((v, canonical, "ascii"))
    fold_map = {v: c for v, c, _ in fold_rows}

    with open(OUT_FOLD, "w", encoding="utf-8", newline="") as fh:
        fh.write("variant\tcanonical\ttier\tvariant_cites\tvariant_dicts\tcanonical_dicts\n")
        for v, c, tier in sorted(fold_rows, key=lambda r: (r[2] != "named", -by_text[r[0]])):
            fh.write(
                f"{v}\t{c}\t{tier}\t{by_text[v]}\t{','.join(sorted(dicts_of[v]))}\t"
                f"{','.join(sorted(dicts_of[c]))}\n"
            )

    # Apply the fold and re-measure reach.
    folded_dicts = collections.defaultdict(set)
    folded_cites = collections.Counter()
    for e in edges:
        t = fold_map.get(e["canonical_text"], e["canonical_text"])
        folded_dicts[t].add(e["dict"])
        folded_cites[t] += e["count"]
    folded_private = [t for t, ds in folded_dicts.items() if len(ds) == 1]
    private_variants = [v for v, c, _ in fold_rows if len(dicts_of[v]) == 1 and len(dicts_of[c] | dicts_of[v]) > 1]
    # Accounting for the private count after the fold: a private variant of a
    # SHARED text disappears (−1 private); a private variant whose canonical is
    # itself private merges into it (−1 private if the same dictionary, −2 if
    # different — the merged node becomes shared).
    private_into_private = [(v, c) for v, c, _ in fold_rows if len(dicts_of[v]) == 1 and len(dicts_of[c]) == 1]
    report["C2b_variant_fold"] = {
        "fold_rows": len(fold_rows),
        "fold_rows_named": sum(1 for r in fold_rows if r[2] == "named"),
        "fold_rows_ascii": sum(1 for r in fold_rows if r[2] == "ascii"),
        "private_nodes_that_are_variants_of_shared_texts": len(private_variants),
        "private_variants_of_shared_by_tier": {
            tier: sum(1 for v, c, t in fold_rows if t == tier and v in private_variants) for tier in ("named", "ascii")
        },
        "private_variants_merging_into_private_canonical": len(private_into_private),
        "private_variants_merging_into_private_canonical_pairs": [f"{v} → {c}" for v, c in private_into_private],
        "nodes_after_fold": len(folded_dicts),
        "private_after_fold": len(folded_private),
        "private_after_fold_pct": round(100.0 * len(folded_private) / len(folded_dicts), 1),
        "private_after_fold_volume_pct": round(100.0 * sum(folded_cites[t] for t in folded_private) / sum(folded_cites.values()), 1),
        "reach_after_fold": reach_table(folded_dicts),
        "reach_after_fold_excluding_thin_rows": reach_table(folded_dicts, frozenset(THIN_ROWS)),
        "texts_cited_by_every_dict_after_fold": sorted(t for t, ds in folded_dicts.items() if len(ds) == len(by_dict)),
        "named_variants": {
            v: {
                "variant_cites": by_text.get(v),
                "variant_dicts": sorted(dicts_of.get(v, ())),
                "canonical_dicts": sorted(dicts_of.get(c, ())),
                "union_dicts": len(dicts_of.get(v, set()) | dicts_of.get(c, set())),
            }
            for v, c in NAMED_VARIANTS.items()
        },
    }

    # ---- A50-C5 kośa citations per dictionary --------------------------------
    report["C5_kosa_citers"] = {}
    for t in KOSAS:
        per = {d: per_dict_text[d][t] for d in per_dict_text if per_dict_text[d][t]}
        if not by_text[t]:
            report["C5_kosa_citers"][t] = {"total": 0, "absent": True}
            continue
        report["C5_kosa_citers"][t] = {
            "total": by_text[t],
            "pwg_share_pct": round(100.0 * per.get("pwg", 0) / by_text[t], 1),
            "per_dict": dict(sorted(per.items(), key=lambda kv: -kv[1])),
            "dicts_citing_at_least_100_times": sorted(d for d, n in per.items() if n >= 100),
        }

    # ---- reproduction of Table 1 / Table 2 figures ---------------------------
    astadhyayi = per_dict_text["pwg"]["Aṣṭādhyāyī (Pāṇini)"] if "pwg" in by_dict else 0
    report["reproduction"] = {
        "table1_distinct_texts": {d: len(per_dict_text[d]) for d in sorted(by_dict)},
        "astadhyayi_pwg_cites": astadhyayi,
        "node_table_n_dicts_mismatches": sum(
            1 for n in nodes if int(n["n_dicts"]) != len(dicts_of[n["canonical_text"]])
        ),
    }

    # ---- provenance drift: committed TSV vs a regenerated edge list -----------
    if os.path.exists(REGEN):
        regen = read_tsv(REGEN)
        for e in regen:
            e["count"] = int(e["count"])
        report["drift"] = drift(edges, regen)
    else:
        report["drift"] = None

    with open(OUT_JSON, "w", encoding="utf-8") as fh:
        json.dump(report, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    print(f"wrote {os.path.relpath(OUT_JSON, ROOT)} and {os.path.relpath(OUT_FOLD, ROOT)}")
    print(json.dumps({k: report[k] for k in ("totals", "C2_reach", "C2b_variant_fold")}, ensure_ascii=False, indent=1)[:3000])
    return 0


if __name__ == "__main__":
    sys.exit(main())
