"""Shared plumbing for the forensic claim pins (H4352, 08-09-2026).

Discipline (from the handoff, locked before any test was written):

* every expected count is derived BY HAND and written literally into the test —
  never produced by running the script under test;
* every fixture is a miniature csl-orig / parsed-cache / correction-file shape
  written by the test itself — never generated by the pipeline it checks;
* every test runs offline: the autouse guard below replaces ``socket.socket`` so
  any network attempt fails loudly instead of silently reaching csl-orig or a
  translation service;
* no live ``../csl-orig`` read — each test points the script's path constants at
  a ``tmp_path`` corpus.

``pin(script, metric, expected, actual)`` asserts equality AND records the row so
the terminal summary prints the expected-vs-actual table the handoff asks for.
"""

import pathlib
import socket
import sys

import pytest

FORENSIC_DIR = pathlib.Path(__file__).resolve().parents[2] / "scripts" / "forensic"
if str(FORENSIC_DIR) not in sys.path:
    sys.path.insert(0, str(FORENSIC_DIR))

TSV_HEADER = "L\tk1\tk2\th\te\tn_cit\tcites"

_PINS = []  # (script, metric, expected, actual)


class NetworkDisabled(RuntimeError):
    """Raised by the offline guard when anything tries to open a socket."""


def _blocked(*_args, **_kwargs):
    raise NetworkDisabled("network is disabled for the forensic pins (H4352)")


@pytest.fixture(autouse=True)
def _no_network(monkeypatch):
    """Offline proof: no test in this directory can open a socket."""
    monkeypatch.setattr(socket, "socket", _blocked)
    monkeypatch.setattr(socket, "create_connection", _blocked)
    yield


@pytest.fixture
def pin():
    """Assert ``actual == expected`` and record the row for the summary table."""

    def _pin(script, metric, expected, actual):
        _PINS.append((script, metric, expected, actual))
        assert actual == expected, (
            f"{script}.{metric}: expected {expected!r} (hand-derived), got {actual!r}"
        )

    return _pin


@pytest.fixture
def forensic_cwd(tmp_path, monkeypatch):
    """A throwaway repo-root stand-in: the scripts write ``data/forensic/*``
    relative to the cwd, so chdir there and pre-create that directory."""
    (tmp_path / "data" / "forensic").mkdir(parents=True)
    monkeypatch.chdir(tmp_path)
    return tmp_path


def write_text(path, text):
    """Write a fixture file, creating parents. Returns the path."""
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def write_tsv(path, rows):
    """Write a ``data/forensic/parsed/<code>.tsv`` cache in the exact column
    order ``parse_cslorig.build_cache`` emits. ``rows`` = (L, k1, k2, h, e,
    n_cit, cites) tuples; ``cites`` is the ``|``-joined citation string."""
    lines = [TSV_HEADER]
    for row in rows:
        lines.append("\t".join(str(x) for x in row))
    return write_text(path, "\n".join(lines) + "\n")


def pytest_terminal_summary(terminalreporter):
    if not _PINS:
        return
    tr = terminalreporter
    tr.write_sep("=", "forensic pins — expected (hand-derived) vs actual")
    tr.write_line("| script | metric | expected | actual | ok |")
    tr.write_line("|---|---|---|---|---|")
    for script, metric, expected, actual in _PINS:
        ok = "yes" if expected == actual else "NO"
        tr.write_line(f"| {script} | {metric} | {expected!r} | {actual!r} | {ok} |")
